[package]
name = "cotp"
version = "0.1.1"
authors = ["replydev <replydev@protonmail.com>"]
edition = "2018"
description = "Trustworthy command line authenticator app compatible with backups from andOTP, Aegis and so on.. "
repository = "https://github.com/replydev/cotp"
homepage = "https://github.com/replydev/cotp"
documentation = "https://github.com/replydev/cotp/blob/master/README.md"
readme = "https://github.com/replydev/cotp/blob/master/README.md"
license-file = "LICENSE"
categories = ["command-line-utilities","authentication"]
keywords = ["cotp","totp","authenticator","google authenticator","argon2"]

[dependencies]
serde_json = "1.0.61"
serde = { version = "1.0.118", features = ["derive"] }
dirs = "3.0.1"
rpassword = "5.0.0"
sodiumoxide = "0.2.6"
base64 = "0.13.0"
ascii = "1.0"
data-encoding = "2.3.1"
err-derive = "0.3.0"
ring = "0.16.19"
