[package]
name = "cotp"
version = "0.1.0"
authors = ["replydev <replydev@protonmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.61"
serde = { version = "1.0.118", features = ["derive"] }
dirs = "3.0.1"
rpassword = "5.0.0"
sodiumoxide = "0.2.6"
base64 = "0.13.0"

[dependencies.otp]
git = "https://github.com/TimDumol/rust-otp"