[package]
name = "cotp"
version = "0.1.7"
authors = ["replydev <replydev@protonmail.com>"]
edition = "2018"
description = "Trustworthy encrypted command line authenticator app compatible with multiple backups."
repository = "https://github.com/replydev/cotp"
homepage = "https://github.com/replydev/cotp"
documentation = "https://github.com/replydev/cotp/blob/master/README.md"
readme = "README.md"
license-file = "LICENSE"
categories = ["command-line-utilities","authentication"]
keywords = ["cotp","totp","authenticator","google-authenticator","argon2"]

[dependencies]
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
dirs = "3.0.2"
rpassword = "5.0.1"
sodiumoxide = "0.2.6"
base64 = "0.13.0"
ascii = "1.0"
data-encoding = "2.3.2"
err-derive = "0.3.0"
ctrlc = "3.1.9"
prettytable-rs = "0.8.0"
oath = "0.10.2"