[package]
name = "cotp"
version = "0.1.0"
authors = ["replydev <replydev@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.60"
sodiumoxide = "0.2.6"
directories = "3.0.1"

[dependencies.otp]
git = "https://github.com/TimDumol/rust-otp"