[package]
name = "cotp"
version = "0.1.0"
authors = ["replydev <replydev@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.60"
serde = { version = "1", features = ["derive"] }
directories = "3.0.1"
regex = "1.4.2"

[dependencies.otp]
git = "https://github.com/TimDumol/rust-otp"