[package]
name = "cotp"
version = "0.1.7"
authors = ["replydev <replydev@protonmail.com>"]
edition = "2018"
description = "Trustworthy encrypted command line authenticator app compatible with multiple backups."
repository = "https://github.com/replydev/cotp"
homepage = "https://github.com/replydev/cotp"
documentation = "https://github.com/replydev/cotp/blob/master/README.md"
readme = "README.md"
license-file = "LICENSE"
categories = ["command-line-utilities","authentication"]
keywords = ["cotp","totp","authenticator","google-authenticator","argon2"]

[dependencies]
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
dirs = "3.0.2"
rpassword = "5.0.1"
sodiumoxide = "0.2.6"
data-encoding = "2.3.2"
totp-lite = "1.0.3"
crossterm = "0.20"
tui = { version = "0.16.0", features = ["crossterm"], default-features = false }