name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Build debug artifacts
    strategy:
      matrix:
        build: [x86_64-linux, aarch64-linux, x86_64-macos, x86_64-win-gnu]
        include:
          - build: x86_64-linux
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - build: aarch64-linux
            os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
          - build: x86_64-macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: x86_64-win-gnu
            os: windows-2019
            target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt update && sudo apt install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev
          fi
        shell: bash

      - name: Run cargo test
        run: cargo test

      - name: Run cargo build
        run: cargo build

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: bins-${{ matrix.build }}
          path: target/debug/cotp*
